name: voicecraft
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.1
  flutter_tts: ^3.6.3
  permission_handler: ^10.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.0  # Add this line

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/listen_button.png
    - assets/speak_button.png
    - assets/profile_image.png
